spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9999

#ratelimiter:
#  instances:
#    inventory:
#      limitForPeriod: 2
#      limitRefreshPeriod: 1s
#      timeoutDuration: 1s