eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

spring:
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://localhost:9999

  jmx:
    enabled: false
  data:
    redis:
#      host: redis-17850.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
#      port: 17850
#      password: uFj8afsiFFSeVxggzlEVUBaL5tkCxFPp
      repositories:
        enabled: true
  redis:
    host: redis-17850.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
    port: 17850
    password: uFj8afsiFFSeVxggzlEVUBaL5tkCxFPp
    expiry:
      time: 86400

resilience4j:
  retry:
    instances:
      retryApiSaveInventory:
        max-attempts: 5
        wait-duration: 5s
  metrics:
    legacy:
      enabled: true
    enabled: true