eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

spring:
  application:
    name: API_GATEWAY
#  config:
#    import: "optional:configserver:"
  cloud:
#    config:
#      uri: http://localhost:9999
    gateway:
      routes:
        - id: AuthService
          uri: ${service.auth.uri}
          predicates:
            - Path=/api/v1/auth/**
#
        - id: ProductService
          uri: ${service.product.uri}
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: EmployeeService
          uri: ${service.employee.uri}
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthenticationFilter

        - id: CustomerService
          uri: ${service.customer.uri}
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: OrderService
          uri: ${service.order.uri}
          predicates:
            - Path=/api/v1/orders/**

        - id: InventoryService
          uri: ${service.inventory.uri}
          predicates:
            - Path=/api/v1/inventories/**
          filters:
            - AuthenticationFilter

#server:
#  port: 8080


